### PR TITLE
feat(deps): upgrade outdated dependencies [AA-7948]

### PR DESCRIPTION
**Pull request by bankyadam**
BREAKING CHANGE:
- if you specified "includeSubdomains" before in your config, update the key to "includeSubDomains"
- upgraded to latest PUG in background
- most koa-* middleware upgraded by mayor version

### CODE REVIEW

**Comment by gergaczd** [comment]
One issue that I found with it so far, that koa-static dropped support for koa 1.x.x based on their changelog and the code:
https://github.com/koajs/static/blob/master/index.js#L58
https://github.com/koajs/static/blob/master/History.md#300--2016-03-24

If we want to drop support for koa 1.x.x then we just need to deprecate this package and use https://github.com/emartech/boar-koa-server instead, this package originally came to life because this package (boar-server) supports 1.x.x and this new one (boar-koa-server) supports koa 2.x.x

**Comment by bankyadam** [comment]
@gergaczd I've downgraded all the packages which did not support koa1.x anymore to the latest which does. By this, we still reached the goal by `npm audit` saying "found 0 vulnerabilities" 🎉

**Comment by gergaczd** [comment]
@bankyadam 
Sorry to drop here the new finding, yesterday I didn't have time to review all the changes.

I found that 'koa-requestid' also dropped support for koa 1 with [version 2.0.0](https://github.com/uphold/koa-requestid/releases/tag/v2.0.0) 

koa-helmet basically downgraded compared to the before PR version (from 3.2.0 to 1.2.0), as I see this is because 3.2.0 does not supported koa 1 either, in that case I guess we should revert the "includeSubdomains" change as well.
Based on a quick search I think nobody using security middlewares from this package, so maybe we can remove it with the breaking change also if it contains security issues.

I am not sure that koa-pug 5.0.0 supports koa 1, I will check it soon.
The other changes are good!

**Review by gergaczd — APPROVED** [review]
I checked and koa-pug 5.0.0 supports koa v1.7.0, I tested it on a dummy project so it is safe.
I think everything is resolved now, safe to merge

**Comment by gergaczd** [comment]
I can't merge it, but it is good from my side!

**Pull request merged**
